# run Cypress tests using CircleCI Cypress orb
# https://github.com/cypress-io/circleci-orb

version: 2.1
orbs:
  cypress: cypress-io/cypress@1
  # for testing on Windows
  # https://circleci.com/docs/2.0/hello-world-windows/
  win: circleci/windows@1

executors:
  node12-lts:
    docker:
      - image: cypress/base:12
  mac:
    macos:
      xcode: "13.0.0"

jobs:
  lint:
    executor: node12-lts
    steps:
      - attach_workspace:
          at: ~/
      - run: npm run types
      - run: npm run lint

workflows:
  build:
    jobs:
      - cypress/run:
          executor: node12-lts
          name: Linux test
          record: true
          start: npm start
      - cypress/run:
          name: Mac test
          executor: mac
          record: true
          start: npm start
          # no need to save the workspace after this job
          no-workspace: true
      - lint:
          requires:
            - Linux test
      - cypress/run:
          name: Windows test
          executor:
            name: win/vs2019
            shell: bash.exe
          record: true
          start: npm start
          # no need to save the workspace after this job
          no-workspace: true
